# Use pnpm
# https://www.seancdavis.com/blog/use-pnpm-with-netlify/
# [build.environment]
#   NPM_FLAGS="--prefix=/dev/null"

# [[plugins]]
#   package = "/.netlify/netlify-plugin-pnpm"
  
[[redirects]]
  from = "/pa/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/pa/api/event"
  to = "https://plausible.io/api/event"
  status = 200
